version: '3.8'

services:
  api:
    build:
      context: ./sdv-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sdv-api:/app
    command: ["cargo", "run"]

  frontend:
    build:
      context: ./sdv-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sdv-web:/app
    command: ["npm", "run", "dev"]
    environment:
      - API_URL=http://api:8000
