name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenchement lors des push sur la branche principale
  pull_request:
    branches:
      - main  # Déclenchement lors des PR vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilise le secret pour le nom d'utilisateur
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilise le secret pour le mot de passe

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .  # Répertoire à partir duquel construire
          push: true  # Pousse l'image vers Docker Hub
          tags: enzowindd/sdv-m1do-containers-project-enzo:latest  # Tag de l'image

      - name: Notify success
        run: echo "Docker image built and pushed successfully!"
