name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Assurez-vous que ce secret est configuré
          password: ${{ secrets.DOCKER_PASSWORD }}  # Assurez-vous que ce secret est configuré

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./sdv-api
          file: ./sdv-api/Dockerfile  # Chemin correct vers le Dockerfile de l'API
          push: true
          tags: enzowindd/sdv-m1do-containers-project-enzo-api:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./sdv-web
          file: ./sdv-web/Dockerfile  # Chemin correct vers le Dockerfile du frontend
          push: true
          tags: enzowindd/sdv-m1do-containers-project-enzo-web:latest
